;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	downcase-region
	ergoemacs-ctl-c
	ergoemacs-paste
	eval-last-sexp
	helm-M-x
	mc/mark-next-lines
	org-self-insert-command
	))

(setq mc/cmds-to-run-once
      '(
	ergoemacs-shortcut
	markdown-exdent-or-delete
	))
